_target_: tactile_learning.deployment.wrappers.deploy_bc.DeployBC
data_path: ??? # This is not used for this particular module tho
robots: ['allegro', 'kinova']
#out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.23/12-16_bc_bs_32_cup_slipping_stacked_cnn
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.26/12-38_bc_bs_32_book_opening_alexnet_pretrained
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/17-34_bc_bs_64_gamepad_alexnet_playfinetuned
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/13-46_bc_bs_32_box_handle_lifting_alexnet
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/21-06_bc_bs_32_bottle_cap_opening_alexnet
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.30/17-05_bc_bs_64_cup_picking
out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.31/18-32_bc_bs_32_bowl_picking
view_num: 1
deployment_run_name: bowl_picking/image_tactile_bc/8