_target_: tactile_learning.deployment.wrappers.deploy_vinn.DeployVINN
out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2022.11.30/12-17_byol_bs_2048_joystick
sensor_indices: [3,7]
allegro_finger_indices: [0,1]
use_encoder: true
only_fingertips: false