_target_: tactile_learning.deployment.wrappers.deploy_vinn.DeployVINN
data_path: ???
# OLD OLD OLD Alexnet play data old
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.19/22-09_tactile_byol_bs_512_tactile_play_data_alexnet_set_normalization

# TASKS 
# Alexnet task data on book opening
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.26/12-29_tactile_byol_bs_512_book_opening_alexnet_pretrained
# gamepad
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/17-20_tactile_byol_bs_64_gamepad_alexnet_pretrained_duration_120
# box handle lifting
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/13-44_tactile_byol_bs_64_box_handle_lifting_alexnet
# bottle cap opening
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/20-52_tactile_byol_bs_64_bottle_cap_opening_alexnet
# cup picking
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.30/15-20_tactile_byol_bs_64_cup_picking
# bowl picking 
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.31/18-31_tactile_byol_bs_64_bowl_picking
# bowl picking - failures included
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.02.05/19-43_tactile_byol_bs_128_bowl_picking_alldata

# Alexnet play data full
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120
# Pads shuffled
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.02.05/01-41_tactile_byol_bs_128_play_data_pad
# Play data for 1 min duration
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.27/15-01_tactile_byol_bs_256_tactile_play_data_alexnet_pretrained_duration_1
# Play data for 5 mins duration
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.26/14-46_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_5
# Play data for 20 mins duration
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.26/15-54_tactile_byol_bs_256_tactile_play_data_alexnet_pretrained_duration_20
# Play data for 80 mins duration
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.26/18-43_tactile_byol_bs_256_tactile_play_data_alexnet_pretrained_duration_80
# Resnet18
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.27/10-50_tactile_byol_bs_128_tactile_play_data_resnet18_pretrained_duration_120
# Stacked CNN
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.27/17-15_tactile_stacked_byol_bs_256_tactile_play_data_stacked_cnn_duration_120
# 3 Layered CNN
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.27/17-25_tactile_byol_bs_256_tactile_play_data_whole_hand_encoder_duration_120
# Single Sensor CNN
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.27/20-53_tactile_byol_bs_1028_tactile_play_data_single_sensor_encoder_duration_120

# Alexnet task data - bottle cap opening
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.24/15-19_tactile_byol_bs_1028_bottle_cap_opening_alexnet
# Alexnet not pretrained task data
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.24/17-47_tactile_byol_bs_512_bottle_cap_opening_alexnet_nonpretrained
# Alexnet not pretrained play data
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.24/17-49_tactile_byol_bs_512_tactile_play_data_alexnet_nonpretrained
# Alexnet not pretrained task data on book opening
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.25/13-26_tactile_byol_bs_128_book_opening_alexnet_nonpretrained
# Stacked play data
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.20/14-05_tactile_stacked_byol_bs_512_tactile_play_data_stacked
# Stacked task data
# cup slipping - tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.22/20-52_tactile_stacked_byol_bs_256_cup_slipping_stacked_byol
# bottle cap opening
# tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.23/21-18_tactile_stacked_byol_bs_512_bottle_cap_opening

# Image byol for box handle lifting
# book opening
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.02.02/19-06_image_byol_bs_32_book_opening
# gamepad
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.02.02/20-46_image_byol_bs_16_gamepad
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/12-14_image_byol_bs_32_box_handle_lifting_resnet18
# bottle cap opening
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.29/19-44_image_byol_bs_32_bottle_cap_opening_alexnet
# cup picking
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.30/13-36_image_byol_bs_32_cup_picking_resnet
# bowl picking
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.31/16-56_image_byol_bs_32_bowl_picking

nn_buffer_size: 15
nn_k: 15
# task_object: cup_slipping
fix_the_thumb: true
sensor_indices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
# sensor_indices: [0,1,3,6,7,10,11,14]
allegro_finger_indices: [0,1,2,3]
robots: ['allegro', 'kinova']
representation_types: ['image', 'tactile'] # observations used in the representations - should add torque here
use_encoder: true
representation_importance: [1,2] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
# deployment_run_name: cup_slipping/cup_left/image_tactile/stacked_/2 # Maybe the other view is better 
deployment_run_name: after_rss/1 # 20 min was not saved 5/9
# deployment_run_name: book_opening/image/3
# demos_to_use: [19,20,21,22,23,24,26] - cup slipping
# demos_to_use: [9,12,18,19,20] # - bottle cap opening
# demos_to_use: [2,4,5,7,8] # book opening
# demos_to_use: [2,3,5,6,7,8] # gamepad joystick down
# demos_to_use: [1,4,9,11,15,17] # box handle lifting
# demos_to_use: [1,4,5,8,9,11] # bottle cap opening
# demos_to_use: [2,3,5,6,7,8] # cup picking
# demos_to_use: [2,5,7,9,15,23] # bowl picking
demos_to_use: [] # after rss
run_the_demo: false # Boolean to indicate if one should only run the demo or deploy vinn or not
single_sensor_tactile: false
stacked_tactile: false
# alexnet_tactile: true
alexnet_nontrained: false
image_nontrained: false
view_num: 1
open_loop: false
sumpool: false 
pca: false
# tactile_shuffle_type: pad # if not given it's considered none
# pca_path: /home/irmak/Workspace/tactile-learning/model_outs/pca_play_data.pkl