mock: false
mock_traj_id: 0
device: cuda
episode_saved_fn: 20230507T204720_14_76

params:
  pretrained: true
  out_dim: 512
  remove_last_layer: true

encoder_targets:
  # - name: resnet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.resnet18
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  # - name: alexnet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.alexnet
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  # - name: mobilenet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.mobilenet_v2
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  # - name: densenet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.densenet_121
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  # - name: googlenet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.googlenet
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  # - name: squeezenet
  #   type: pretrained
  #   encoder:
  #     _target_: tactile_learning.models.squeezenet
  #     pretrained: ???
  #     out_dim: ???
  #     remove_last_layer: ???
  - name: bc_model # These will be loaded by using init_encoder_info
    type: trained
    out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.11/13-21_bc_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
    # encoder:
    #   _target_: tactile_learning.models.load_model
    #   cfg: ???
    #   device: ???
    #   model_path: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.11/13-21_bc_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss/models/bc_image_encoder_best.pt
    #   bc_model_type: image 

# trained_targets: