defaults:
  - deployer: bc_gmm

visualize: true
loop: true
frequency: 1.5
deployment_dump_dir: /home/irmak/Workspace/tactile-learning/deployment_data/book_opening/after_rss/bc_gmm/1
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/book_opening/after_rss # User should fill this