deploy_module: 
  _target_: tactile_learning.deployment.wrappers.deploy_bc.DeployBC
  out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2022.11.25/18-02_bc

frequency: 15
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data
