defaults:
  - deploy_module: vinn_all

robots: [allegro, kinova]
visualize: true
loop: true
frequency: 15
object: box_handle_lifting/box_location_changing/eval
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}
