defaults:
  - deployer: vinn

visualize: false
loop: true
frequency: 1
deployment_dump_dir: /home/irmak/Workspace/tactile-learning/deployment_data/cup_picking/after_rss/fixing_blur/1
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/cup_picking/after_rss # User should fill this