defaults:
  - deployer: vinn

visualize: true
loop: true
frequency: 1.2
deployment_dump_dir: /home/irmak/Workspace/tactile-learning/deployment_data/bowl_picking/after_rss/original_object/2
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/bowl_picking/after_rss # User should fill this