deploy_module: 
  # _target_: tactile_learning.deployment.wrappers.deploy_bc.DeployBC
  # out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2022.11.28/00-34_bc
  _target_: tactile_learning.deployment.wrappers.deploy_vinn.DeployVINN
  out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2022.11.30/12-17_byol_bs_2048_joystick
  # out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2022.12.05/22-33_byol_bs_256_joystick_2
  sensor_indices: [3,7]
  allegro_finger_indices: [0,1]
  use_encoder: true
  only_fingertips: false

visualize: true
loop: false
frequency: 15
object: joystick
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}
