defaults:
  - deployer: bet # This fails almost anywhere! 

visualize: false
loop: true
frequency: 4
deployment_dump_dir: null
# deployment_dump_dir: /home/irmak/Workspace/tactile-learning/deployment_data/book_opening/after_rss/bc_gmm/1
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/mint_opening # User should fill this