
preprocessor_module:
  _target_: tactile_learning.preprocess.Preprocessor
  data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/preprocess_test_demos
  modules:
    robot: ${robot_cfg}
    image: ${image_cfg}
    touch: ${touch_cfg}
  dump_data_indices: true
  process_single_demo: false

robot_cfg:
  _target_: tactile_learning.preprocess.RobotPreprocessor
  subsample_separately: true
  robot_names: ['allegro', 'kinova']
  robot_thresholds: 
    hand: 0.008
    arm: 0.012 # corresponding thresholds to the robot_names
  dump_fingertips: true

image_cfg:
  _target_: tactile_learning.preprocess.ImagePreprocessor
  camera_id: 0
  is_ssl: false
  time_difference: null # If the 

touch_cfg:
  _target_: tactile_learning.preprocess.TouchPreprocessor