# data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/box_handle_lifting/box_location_changing/training
# data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/box_handle_lifting/box_location_changing/eval
# data_path: /home/irmak/Workspace/Holo-Bot/deployment_data/box_handle_lifting
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/tactile_play_data
# data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/tactile_play_data/demonstration_hand_touching_itself_record_2
process_single_demo: false
vision_byol: false
tactile_byol: true
dump_images: false
view_num: 0