data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/cup_picking/after_rss
process_single_demo: false

# Preprocessing for different types - if both false then preprocessing is done for deployment
vision_byol: true
tactile_byol: false

subsample_separately: true
dump_images: true # If vision_byol is used dump_images should be true
dump_data_indices: true 
dump_fingertips: true
threshold_step_size: 0.012 # Step size to be used in subsampling
view_num: 1 # Camera ID to dump the images