defaults:
  - suite: gym
  - agent: fish # Optimizer will be initialized inside the agent

object: bowl_picking
data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}/after_rss
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/00-59_image_byol_bs_32_cup_picking_after_rss
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.11/13-21_bc_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120 # - Play data encoder
tactile_model_type: byol # It could be ssl/byol as well
image_model_type: bc

reward_representations: ['image']
policy_representations: ['image', 'features']

seed: 42 
device: cuda

num_train_frames: 10000 # Total training numbers
num_seed_frames: 0 # First 10 episodes will be random!

eval_every_frames: 100
buffer_path: 2023.05.22T16-20_last_frames_5_se_False_endrepeat_1_mfb_True_ee_False_offset_lowered # If there is a buffer path given this will be used

# FISH and environment params
expert_id: 0 # 22
expert_demo_nums: [22,24,28,29,34] # We can get multiple expert demos
reward_matching_steps: 5 # We will only match the last 20 steps through the demonstration
match_from_both: True # If true we'll match the rewards from both of the 
exponential_weight_init: False # If true the initial weight in the ot reward will be exponential - currently it's equal importance to all timeframes
end_frames_repeat: 1 # Stack the last frames for 20 times
sum_experts: False
scale_representations: False
exponential_exploration: False # This is to explore sometimes when it's stuck
mock_env: False # If set to true we will be using mock demos as the environment interaction
mock_demo_nums: [10, 12, 13, 15, 2, 7] # Use all of them # [13,15,2,7] # 15 is the expert demo in the agent
camera_num: 1

# Agent params 
bc_regularize: False
features_repeat: 5 # Number to how many times to repeat the features as the input to the model

# Replay buffer params
replay_buffer_size: 150000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256

# Recorder
save_video: False 
save_train_video: True 
save_train_cost_matrices: True

# Snapshot loading
load_snapshot: False
snapshot_weight: /home/irmak/Workspace/tactile-learning/weights/snapshot_rewards_fixed.pt # This should be set if we ask it to load snapshot - but for now we're not

log: False
experiment: ${now:%Y.%m.%d}T${now:%H-%M}_last_frames_${reward_matching_steps}_se_${sum_experts}_endrepeat_${end_frames_repeat}_mfb_${match_from_both}_ee_${exponential_exploration}_offset_lowered

# hydra configuration - should be received separately
hydra:
    run:
        dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}

