defaults:
    - learner: bet
    - dataset: bet # tactile_tdex_dataset

seed: 42
device: cuda

learner_type: bet # Can be bet, image_byol, tactile_stacked_byol # tactile_stacked_byol tactile_linear_byol, bc, tactile_byol
self_supervised: true

# Demos to use 
# demos_to_use: [2,3,5,6,7,9] # Gamepad
# demos_to_use: [2,5,8,10,11,12]  # Bottle Cap Opening
demos_to_use: [3,4,5,6,8,10] 

# Hyperparameters to be used everywhere
batch_size: 32
tactile_image_size: 224 # This could be changed for stacked or shared architectures
vision_image_size: 480
train_epochs: 1000
save_frequency: 10
train_dset_split: 0.90

distributed: false
num_workers: 4

# Data path to be set
object: book_opening
experiment: ${learner_type}_bs_${batch_size}_${object}_after_rss # Name of the experiment that the models are saved
data_dir: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}/after_rss
checkpoint_dir: ??? # Will be set to hydra dir inside the code

# logger
logger: true # To init logger or not
log_frequency: 1

# hydra configuration - should be received separately
hydra:
    run:
        dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}
