gmm_layer:
  _target_: tactile_learning.models.GMMLayer
  obs_dim: 1536
  action_dim: 23
  num_gaussians: 64
  hidden_dims: [512, 128, 64]

tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120
#image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/00-59_image_byol_bs_32_cup_picking_after_rss
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss 
freeze_encoders: true
representation_type: tdex
view_num: 1