
momentum: 0.9
temperature: 0.1

expander:
  input_dim: 9216
  hidden_sizes: [8192]
  use_batchnorm: true

predictor:
  # Input size is the encoder's output size
  _target_: tactile_learning.models.create_fc
  input_dim: ??? 
  output_size: 8192
  hidden_sizes: [8192]
  enable_batchnorm: true

