_target_: tactile_learning.datasets.all.TactileVisionActionDataset
data_path: ???
tactile_information_type: whole_hand #whole_hand, stacked - bc we use alexnet now
tactile_img_size: ???
vision_view_num: 1