_target_: tactile_learning.datasets.tactile.TactileSmallDataset
data_path: ???
sensor_grid: [1,2]
sensor_indices: [3,7]
allegro_finger_indices: [0,1]
fingertip_stats:
  - [0.0560708, 0.02560598, 0.11358902] # Mean
  - [0.0161393, 0.02516701, 0.01390676] # Std

