_target_: tactile_learning.datasets.tactile.TactileBYOLDataset
data_path: ???
tactile_information_type: whole_hand
img_size: 224
mean_std: # These values should be found through notebook
  - [ 0.1218,  0.7076, 12.5459] 
  - [168.1889,  98.6576, 104.8352]
min_max: 
  - [-107.0494, -172.3380,  -84.2302] 
  - [112.6702, 142.1870, 130.8831]