_target_: tactile_learning.agents.rewarder.sinkhorn_cosine.SinkhornCosine
expert_demos: ???
image_encoder: ??? 
tactile_encoder: ???
exponential_weight_init: False
device: 2
sinkhorn_rew_scale: 10 # This gets updated anyways
representation_types: ${reward_representations}
expert_frame_matches: ${expert_frame_matches}
episode_frame_matches: ${episode_frame_matches}