_target_: tactile_learning.deployers.BCGMM
deployment_dump_dir: ??? 
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.06/10-48_bc_gmm_bs_32_epochs_200_lr_1e-05_cup_picking_after_rss
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/14-21_bc_gmm_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss 
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/13-52_bc_gmm_bs_16_epochs_500_lr_1e-05_gamepad_after_rss 
# out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/13-51_bc_gmm_bs_16_epochs_500_lr_1e-05_bottle_opening_after_rss
out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/17-45_bc_gmm_bs_32_epochs_500_lr_1e-05_book_opening_after_rss
view_num: 1
representation_type: tdex