_target_: tactile_learning.deployers.BET
data_path: ??? 
deployment_dump_dir: ???
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/00-59_image_byol_bs_32_cup_picking_after_rss
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/00-13_image_byol_bs_32_epochs_500_lr_1e-05_gamepad_after_rss 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.09/17-10_image_byol_bs_32_epochs_500_lr_1e-05_bottle_opening_after_rss 
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/16-16_image_byol_bs_33_epochs_500_lr_1e-05_book_opening_after_rss 

# bet_model_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/15-47_bet_bs_32_cup_picking_after_rss
# bet_model_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/13-55_bet_bs_32_bowl_picking_after_rss 
# bet_model_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/13-29_bet_bs_32_gamepad_after_rss
# bet_model_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/13-41_bet_bs_32_bottle_opening_after_rss 
bet_model_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/17-34_bet_bs_32_book_opening_after_rss 

seq_length: 3
representation_types: ['image', 'tactile', 'kinova', 'allegro'] # Observations used in the representations
# demos_to_use: [22,24,26,34,28,29] # Bowl Unstacking
# demos_to_use: [2,3,5,6,7,9] # Gamepad
# demos_to_use: [2,5,8,10,11,12] # Bottle Opening
demos_to_use: [3,4,5,6,8,10] 
view_num: 1