_target_: tactile_learning.deployers.VINN
data_path: ???

# Directories to change by the user depending on where they saved the data
# deployment_dump_dir: /home/irmak/Workspace/tactile-learning/deployment_data/cup_picking/after_rss/10
deployment_dump_dir: ???
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/00-59_image_byol_bs_32_cup_picking_after_rss # CUP PICKING 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.04/18-56_tactile_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss # Bowl picking old

# TISH corl baselines
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.05/19-59_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_turning_frame_diff_5_resnet 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.04/21-28_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_flipping_frame_diff_5_resnet 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.02/21-37_temporal_ssl_bs_32_epochs_1000_lr_1e-05_plier_picking_frame_diff_8
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/22-59_temporal_ssl_bs_32_epochs_1000_view_0_peg_insertion_frame_diff_5_resnet 
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/18-27_temporal_ssl_bs_32_epochs_1000_view_1_bowl_picking_frame_diff_5_resnet

image_model_type: temporal # NOTE: Make sure that you fix this
nn_buffer_size: 15
nn_k: 15
representation_types: ['image', 'tactile'] # Observations used in the representations
representation_importance: [1,1] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
# cup_picking_demos_to_use: [13,14,15,16,17,18] # Leave empty to use all the demos in the evaluation
# demos_to_use: [22,24,26,34,28,29]

# demos_to_use: [25] # Sponge flipping
# demos_to_use: [16] # Card Turning
# demos_to_use: [15] # Plier picking
# demos_to_use: [4] # Peg Insertion
demos_to_use: [22]

view_num: 1
open_loop: false

dump_deployment_info: false