image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/18-27_temporal_ssl_bs_32_epochs_1000_view_1_bowl_picking_frame_diff_5_resnet
image_model_type: temporal 

# Joint temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-02_temporal_ssl_bowl_picking_view_1_resnet
# image_model_type: temporal

#contrastive temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/17-26_temporal_ssl_bowl_picking_view_1_contrastive_resnet
# image_model_type: temporal

#BYOL
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
# image_model_type: byol

#BC
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-20_bc_bowl_picking_view_1_resnet
# image_model_type: bc

#pretrained
# image_out_dir: null 
# image_model_type: pretrained

vinn_image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
vinn_image_model_type: byol

data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/bowl_picking

name: bowl_unstacking
task_name: BowlUnstacking-v1
camera_num: 1

expert_demo_nums: [22] # [24]
hand_offset_scale_factor: 0.3 
arm_offset_scale_factor: 0.05 
offset_mask: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

action_type: robot

