image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/22-59_temporal_ssl_bs_32_epochs_1000_view_0_peg_insertion_frame_diff_5_resnet # peg insertion 
image_model_type: temporal # TODO: Add this information to the config - or get it from the learner type and etc

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/peg_insertion

name: peg_insertion