image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.02/21-37_temporal_ssl_bs_32_epochs_1000_lr_1e-05_plier_picking_frame_diff_8
image_model_type: temporal

# Joint temporal
# '/home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/14-18_temporal_ssl_plier_picking_view_0_joint_resnet',
# 'temporal'

# Contrastive Temporal
# '/home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/14-19_temporal_ssl_plier_picking_view_0_contrastive_resnet',
# 'temporal'

# BYOL 
# '/home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/18-14_image_byol_plier_picking_view_0_resnet',
# 'byol'

# BC 
# '/home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-18_bc_plier_picking_view_0_resnet',
# 'bc'

# Pretrained
# image_out_dir: null 
# image_model_type: pretrained

vinn_image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/18-14_image_byol_plier_picking_view_0_resnet
vinn_image_model_type: byol

data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/plier_picking

name: plier_picking

expert_demo_nums: [15] # 25? 
arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.25
offset_mask: [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]