_target_: tactile_learning.deployment.wrappers.deploy_vinn.DeployVINN
out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.02/19-29_byol_bs_1028_box_handle_lifting
nn_buffer_size: 100
nn_k: 20
sensor_indices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
allegro_finger_indices: [0,1,2,3]
robots: ['allegro', 'kinova']
use_encoder: true
only_states: false