_target_: tactile_learning.deployment.wrappers.deploy_vinn.DeployVINN
data_path: ???
tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.14/20-07_tactile_byol_bs_1028_tactile_play_data_single_sensor_encoder_out_dim_8
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.10/20-22_image_byol_bs_32_box_handle_lifting/box_location_changing/training
nn_buffer_size: 5
nn_k: 5
task_object: gamepad
sensor_indices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
# sensor_indices: [0,1,3,6,7,10,11,14]
allegro_finger_indices: [0,1,2,3]
robots: ['allegro', 'kinova']
use_encoder: true
representation_types: ['image', 'tactile'] # observations used in the representations
deployment_run_name: gamepad/right/image_tactile/nontrained/11
demos_to_use: []
run_the_demo: false # Boolean to indicate if one should only run the demo or deploy vinn or not
single_sensor_tactile: false
stacked_tactile: false
alexnet_tactile: true
alexnet_nontrained: true
image_nontrained: true
view_num: 0